language: ruby
rvm:
  - 2.6
before_install:
  - nvm install 17.3.0
  - sudo apt-get update
  - sudo apt-get install -y imagemagick libmagickcore-dev libmagickwand-dev

install:
  - gem install bundler
  - bundle install
  - npm install
  - bundle exec jekyll build
  - NODE_ENV=production npm run build
script:
  - bundle exec jekyll build
  - bundle exec htmlproofer ./_site --disable-external

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: blog
  local-dir: _site
  target-branch: master
