url: "https://thebroken.link"
permalink: /:title/
plugins:
  - jekyll-last-modified-at
markdown: redcarpet
exclude: [
  "Gemfile",
  "Gemfile.lock",
  "README.md",
  "tailwind.config.js",
  "package.json",
  "package-lock.json",
  "postcss.config.js",
  "css",
  "node_modules",
]
redcarpet:
  extensions: [
    "strikethrough",
    "no_intra_emphasis",
    "superscript",
    "with_toc_data"
  ]
